# Generated by Django 3.2.7 on 2021-09-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_taskdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(default='{}')),
            ],
        ),
    ]
