# Generated by Django 3.2.7 on 2021-09-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historydate', models.TextField(default='{}')),
            ],
        ),
    ]
